services:
  frontend:
    image: computers33333/airaccidentdata-frontend:latest
    ports:
      - 3000:3000
    env_file:
      - .env

  backend:
    image: computers33333/airaccidentdata-backend:latest
    ports:
      - 8080:8080
    env_file:
      - .env

  aircraft_scraper:
    image: computers33333/airaccidentdata-aircraft_scraper:latest
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/production.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
