services:
  frontend:
    image: computers33333/airaccidentdata-frontend
    ports:
      - 3000:3000
    env_file:
      - .env

  backend:
    image: computers33333/airaccidentdata-backend
    ports:
      - 8080:8080
    env_file:
      - .env

  aircraft_scraper:
    image: computers33333/airaccidentdata-aircraft_scraper
    volumes:
      - ./aircraft_scraper:/app 
      - /app/node_modules 
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_airaccidentdata_prod:/var/lib/mysql
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/production.conf:/etc/nginx/nginx.conf

volumes:
  mysql_airaccidentdata_prod:
    driver: local
