# Use the official Go image as the base image
FROM golang:latest

# Install necessary packages
RUN apt-get update && apt-get install -y \
    mysql-client \
    wget \
    && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt install -y ./google-chrome-stable_current_amd64.deb \
    && rm -f google-chrome-stable_current_amd64.deb

# Set the working directory for your application
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Expose port 8080
EXPOSE 8080

# Command to run the application
CMD ["go", "run", "main.go"]
