# Use the official Debian-based Go image
FROM golang:1.20

# Install necessary packages
RUN apt-get update && apt-get install -y \
    default-mysql-client \
    wget \
    && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt install -y ./google-chrome-stable_current_amd64.deb \
    && rm -f google-chrome-stable_current_amd64.deb

# Set the working directory for your application
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Expose port 8080
EXPOSE 8080

# Run the initialization script and start the Go application
CMD ["sh", "-c", "/app/init-db.sh"]
