CREATE DATABASE IF NOT EXISTS airaccidentdata;
USE airaccidentdata;

CREATE TABLE IF NOT EXISTS AircraftAccidents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    updated VARCHAR(255),
    entry_date DATE,
    event_local_date DATE,
    event_local_time TIME,
    location_city_name VARCHAR(255),
    location_state_name VARCHAR(255),
    location_country_name VARCHAR(255),
    remark_text TEXT,
    event_type_description VARCHAR(255),
    fsdo_description VARCHAR(255),
    registration_number VARCHAR(255) UNIQUE,
    flight_number VARCHAR(255),
    aircraft_operator VARCHAR(255),
    aircraft_make_name VARCHAR(255),
    aircraft_model_name VARCHAR(255),
    aircraft_missing_flag VARCHAR(50),
    aircraft_damage_description VARCHAR(255),
    flight_activity VARCHAR(255),
    flight_phase VARCHAR(255),
    far_part VARCHAR(50),
    max_injury_level VARCHAR(50),
    fatal_flag VARCHAR(50),
    flight_crew_injury_none INT,
    flight_crew_injury_minor INT,
    flight_crew_injury_serious INT,
    flight_crew_injury_fatal INT,
    flight_crew_injury_unknown INT,
    cabin_crew_injury_none INT,
    cabin_crew_injury_minor INT,
    cabin_crew_injury_serious INT,
    cabin_crew_injury_fatal INT,
    cabin_crew_injury_unknown INT,
    passenger_injury_none INT,
    passenger_injury_minor INT,
    passenger_injury_serious INT,
    passenger_injury_fatal INT,
    passenger_injury_unknown INT,
    ground_injury_none INT,
    ground_injury_minor INT,
    ground_injury_serious INT,
    ground_injury_fatal INT,
    ground_injury_unknown INT
);

-- Insert a single record into AircraftAccidents
INSERT INTO AircraftAccidents (
    updated, entry_date, event_local_date, event_local_time, 
    location_city_name, location_state_name, location_country_name, 
    remark_text, event_type_description, fsdo_description, 
    registration_number, flight_number, aircraft_operator, 
    aircraft_make_name, aircraft_model_name, aircraft_missing_flag, 
    aircraft_damage_description, flight_activity, flight_phase, 
    far_part, max_injury_level, fatal_flag, 
    flight_crew_injury_none, flight_crew_injury_minor, 
    flight_crew_injury_serious, flight_crew_injury_fatal, 
    flight_crew_injury_unknown, cabin_crew_injury_none, 
    cabin_crew_injury_minor, cabin_crew_injury_serious, 
    cabin_crew_injury_fatal, cabin_crew_injury_unknown, 
    passenger_injury_none, passenger_injury_minor, 
    passenger_injury_serious, passenger_injury_fatal, 
    passenger_injury_unknown, ground_injury_none, 
    ground_injury_minor, ground_injury_serious, 
    ground_injury_fatal, ground_injury_unknown
) VALUES (
    '2024-02-16', '2024-02-16', '2024-02-15', '14:30:00', 
    'Springfield', 'Illinois', 'USA', 
    'Aircraft experienced engine failure during flight', 'Incident', 'Springfield FSDO', 
    'N12345', 'FL123', 'Airline XYZ', 
    'Boeing', '737-800', 'No', 
    'Minor', 'Commercial Air Transport', 'Cruise', 
    'Part 121', 'None', 'No', 
    2, 0, 
    0, 0, 
    0, 1, 
    0, 0, 
    0, 0, 
    100, 2, 
    0, 0, 
    0, 0, 
    0, 0, 
    0, 0
);

-- Insert another record into AircraftAccidents
INSERT INTO AircraftAccidents (
    updated, entry_date, event_local_date, event_local_time, 
    location_city_name, location_state_name, location_country_name, 
    remark_text, event_type_description, fsdo_description, 
    registration_number, flight_number, aircraft_operator, 
    aircraft_make_name, aircraft_model_name, aircraft_missing_flag, 
    aircraft_damage_description, flight_activity, flight_phase, 
    far_part, max_injury_level, fatal_flag, 
    flight_crew_injury_none, flight_crew_injury_minor, 
    flight_crew_injury_serious, flight_crew_injury_fatal, 
    flight_crew_injury_unknown, cabin_crew_injury_none, 
    cabin_crew_injury_minor, cabin_crew_injury_serious, 
    cabin_crew_injury_fatal, cabin_crew_injury_unknown, 
    passenger_injury_none, passenger_injury_minor, 
    passenger_injury_serious, passenger_injury_fatal, 
    passenger_injury_unknown, ground_injury_none, 
    ground_injury_minor, ground_injury_serious, 
    ground_injury_fatal, ground_injury_unknown
) VALUES (
    '2024-02-16', '2024-02-16', '2024-02-14', '09:00:00', 
    'Los Angeles', 'California', 'USA', 
    'Landing gear malfunctioned during landing', 'Accident', 'Los Angeles FSDO', 
    'N54321', 'FL321', 'Airline ABC', 
    'Airbus', 'A320', 'No', 
    'Substantial', 'Commercial Air Transport', 'Landing', 
    'Part 121', 'Minor', 'No', 
    0, 1, 
    1, 0, 
    0, 2, 
    0, 0, 
    0, 0, 
    150, 5, 
    10, 2, 
    0, 1, 
    0, 0, 
    0, 0
);
