// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accidents": {
            "get": {
                "description": "Get list of all aviation accidents with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accidents"
                ],
                "summary": "Get a list of accidents",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of accidents per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AccidentResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/accidents/byId/{id}": {
            "get": {
                "description": "Retrieve details of an accident by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accidents"
                ],
                "summary": "Get an accident by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Accident ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AircraftAccident"
                        }
                    },
                    "400": {
                        "description": "Invalid accident ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Accident not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/aircrafts": {
            "get": {
                "description": "Retrieve a list of all aircraft.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aircrafts"
                ],
                "summary": "Get a list of aircrafts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Aircraft"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/aircrafts/byId/{id}": {
            "get": {
                "description": "Retrieve details of an aircraft by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aircrafts"
                ],
                "summary": "Get an aircraft by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Aircraft ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Aircraft"
                        }
                    },
                    "400": {
                        "description": "Invalid aircraft ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Aircraft not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/aircrafts/{registration_number}/accidents": {
            "get": {
                "description": "Get details of an aviation accident by its registration number",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aircrafts"
                ],
                "summary": "Get a list of accidents by aircraft registration number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Registration number of the aircraft",
                        "name": "registration_number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Accident details",
                        "schema": {
                            "$ref": "#/definitions/models.AccidentDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid registration number",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Accident not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AccidentDetailResponse": {
            "type": "object",
            "properties": {
                "accidents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AircraftAccident"
                    }
                },
                "aircraft_make_name": {
                    "type": "string"
                },
                "aircraft_model_name": {
                    "type": "string"
                },
                "aircraft_operator": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "registration_number": {
                    "type": "string"
                }
            }
        },
        "models.AccidentResponse": {
            "type": "object",
            "properties": {
                "accidents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AircraftAccident"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.Aircraft": {
            "type": "object",
            "properties": {
                "accidents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AircraftAccident"
                    }
                },
                "aircraft_make_name": {
                    "type": "string"
                },
                "aircraft_model_name": {
                    "type": "string"
                },
                "aircraft_operator": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "registration_number": {
                    "type": "string"
                }
            }
        },
        "models.AircraftAccident": {
            "type": "object",
            "properties": {
                "aircraft_damage_description": {
                    "type": "string"
                },
                "aircraft_id": {
                    "type": "integer"
                },
                "aircraft_missing_flag": {
                    "type": "string"
                },
                "cabin_crew_injury_fatal": {
                    "type": "integer"
                },
                "cabin_crew_injury_minor": {
                    "type": "integer"
                },
                "cabin_crew_injury_none": {
                    "type": "integer"
                },
                "cabin_crew_injury_serious": {
                    "type": "integer"
                },
                "cabin_crew_injury_unknown": {
                    "type": "integer"
                },
                "entry_date": {
                    "type": "string"
                },
                "event_local_date": {
                    "type": "string"
                },
                "event_local_time": {
                    "type": "string"
                },
                "event_type_description": {
                    "type": "string"
                },
                "far_part": {
                    "type": "string"
                },
                "fatal_flag": {
                    "type": "string"
                },
                "flight_activity": {
                    "type": "string"
                },
                "flight_crew_injury_fatal": {
                    "type": "integer"
                },
                "flight_crew_injury_minor": {
                    "type": "integer"
                },
                "flight_crew_injury_none": {
                    "type": "integer"
                },
                "flight_crew_injury_serious": {
                    "type": "integer"
                },
                "flight_crew_injury_unknown": {
                    "type": "integer"
                },
                "flight_number": {
                    "type": "string"
                },
                "flight_phase": {
                    "type": "string"
                },
                "fsdo_description": {
                    "type": "string"
                },
                "ground_injury_fatal": {
                    "type": "integer"
                },
                "ground_injury_minor": {
                    "type": "integer"
                },
                "ground_injury_none": {
                    "type": "integer"
                },
                "ground_injury_serious": {
                    "type": "integer"
                },
                "ground_injury_unknown": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "location_city_name": {
                    "type": "string"
                },
                "location_country_name": {
                    "type": "string"
                },
                "location_state_name": {
                    "type": "string"
                },
                "max_injury_level": {
                    "type": "string"
                },
                "passenger_injury_fatal": {
                    "type": "integer"
                },
                "passenger_injury_minor": {
                    "type": "integer"
                },
                "passenger_injury_none": {
                    "type": "integer"
                },
                "passenger_injury_serious": {
                    "type": "integer"
                },
                "passenger_injury_unknown": {
                    "type": "integer"
                },
                "remark_text": {
                    "type": "string"
                },
                "updated": {
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "AirAccidentData API",
	Description:      "API server for airaccidentdata.com",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
