basePath: /api/v1
definitions:
  models.AccidentResponse:
    properties:
      accidents:
        items:
          $ref: '#/definitions/models.AircraftAccident'
        type: array
      limit:
        type: integer
      page:
        type: integer
      total:
        type: integer
    type: object
  models.AircraftAccident:
    properties:
      aircraftDamageDescription:
        type: string
      aircraftMakeName:
        type: string
      aircraftMissingFlag:
        type: string
      aircraftModelName:
        type: string
      aircraftOperator:
        type: string
      cabinCrewInjuryFatal:
        type: integer
      cabinCrewInjuryMinor:
        type: integer
      cabinCrewInjuryNone:
        type: integer
      cabinCrewInjurySerious:
        type: integer
      cabinCrewInjuryUnknown:
        type: integer
      entryDate:
        type: string
      eventLocalDate:
        type: string
      eventLocalTime:
        type: string
      eventTypeDescription:
        type: string
      farPart:
        type: string
      fatalFlag:
        type: string
      flightActivity:
        type: string
      flightCrewInjuryFatal:
        type: integer
      flightCrewInjuryMinor:
        type: integer
      flightCrewInjuryNone:
        type: integer
      flightCrewInjurySerious:
        type: integer
      flightCrewInjuryUnknown:
        type: integer
      flightNumber:
        type: string
      flightPhase:
        type: string
      fsdoDescription:
        type: string
      groundInjuryFatal:
        type: integer
      groundInjuryMinor:
        type: integer
      groundInjuryNone:
        type: integer
      groundInjurySerious:
        type: integer
      groundInjuryUnknown:
        type: integer
      id:
        type: integer
      locationCityName:
        type: string
      locationCountryName:
        type: string
      locationStateName:
        type: string
      maxInjuryLevel:
        type: string
      passengerInjuryFatal:
        type: integer
      passengerInjuryMinor:
        type: integer
      passengerInjuryNone:
        type: integer
      passengerInjurySerious:
        type: integer
      passengerInjuryUnknown:
        type: integer
      registrationNumber:
        type: string
      remarkText:
        type: string
      updated:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: API server for airaccidentdata.com
  title: AirAccidentData API
  version: "1.0"
paths:
  /accidents:
    get:
      description: Get list of all aviation accidents with pagination
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of accidents per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AccidentResponse'
        "400":
          description: Invalid parameters
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get list of Accidents
      tags:
      - Accidents
swagger: "2.0"
