basePath: /api/v1
definitions:
  models.Accident:
    properties:
      aircraft_damage_description:
        type: string
      aircraft_id:
        type: integer
      aircraft_missing_flag:
        type: string
      entry_date:
        type: string
      event_local_date:
        type: string
      event_local_time:
        type: string
      event_type_description:
        type: string
      far_part:
        type: string
      fatal_flag:
        type: string
      flight_activity:
        type: string
      flight_number:
        type: string
      flight_phase:
        type: string
      fsdo_description:
        type: string
      id:
        type: integer
      location_id:
        type: integer
      remark_text:
        type: string
      updated:
        type: string
    type: object
  models.AccidentPaginatedResponse:
    properties:
      accidents:
        items:
          $ref: '#/definitions/models.Accident'
        type: array
      limit:
        type: integer
      page:
        type: integer
      total:
        type: integer
    type: object
  models.Aircraft:
    properties:
      aircraft_make_name:
        type: string
      aircraft_model_name:
        type: string
      aircraft_operator:
        type: string
      id:
        type: integer
      registration_number:
        type: string
    type: object
  models.AircraftPaginatedResponse:
    properties:
      aircrafts:
        items:
          $ref: '#/definitions/models.Aircraft'
        type: array
      limit:
        type: integer
      page:
        type: integer
      total:
        type: integer
    type: object
  models.ErrorResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: API server for airaccidentdata.com
  title: AirAccidentData API
  version: "1.0"
paths:
  /accidents:
    get:
      description: Get a list of all aviation accidents
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of accidents per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AccidentPaginatedResponse'
        "400":
          description: Invalid parameters
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get a list of accidents
      tags:
      - Accidents
  /aircrafts:
    get:
      description: Retrieve a list of all aircrafts.
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of aircraft per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Aircrafts data with pagination details
          schema:
            $ref: '#/definitions/models.AircraftPaginatedResponse'
        "400":
          description: Invalid parameters
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get a list of aircrafts
      tags:
      - Aircrafts
swagger: "2.0"
