basePath: /api/v1
definitions:
  models.AccidentDetailResponse:
    properties:
      accidents:
        items:
          $ref: '#/definitions/models.AircraftAccident'
        type: array
      aircraft_make_name:
        type: string
      aircraft_model_name:
        type: string
      aircraft_operator:
        type: string
      id:
        type: integer
      registration_number:
        type: string
    type: object
  models.AccidentResponse:
    properties:
      accidents:
        items:
          $ref: '#/definitions/models.AircraftAccident'
        type: array
      limit:
        type: integer
      page:
        type: integer
      total:
        type: integer
    type: object
  models.Aircraft:
    properties:
      accidents:
        items:
          $ref: '#/definitions/models.AircraftAccident'
        type: array
      aircraft_make_name:
        type: string
      aircraft_model_name:
        type: string
      aircraft_operator:
        type: string
      id:
        type: integer
      registration_number:
        type: string
    type: object
  models.AircraftAccident:
    properties:
      aircraft_damage_description:
        type: string
      aircraft_id:
        type: integer
      aircraft_missing_flag:
        type: string
      cabin_crew_injury_fatal:
        type: integer
      cabin_crew_injury_minor:
        type: integer
      cabin_crew_injury_none:
        type: integer
      cabin_crew_injury_serious:
        type: integer
      cabin_crew_injury_unknown:
        type: integer
      entry_date:
        type: string
      event_local_date:
        type: string
      event_local_time:
        type: string
      event_type_description:
        type: string
      far_part:
        type: string
      fatal_flag:
        type: string
      flight_activity:
        type: string
      flight_crew_injury_fatal:
        type: integer
      flight_crew_injury_minor:
        type: integer
      flight_crew_injury_none:
        type: integer
      flight_crew_injury_serious:
        type: integer
      flight_crew_injury_unknown:
        type: integer
      flight_number:
        type: string
      flight_phase:
        type: string
      fsdo_description:
        type: string
      ground_injury_fatal:
        type: integer
      ground_injury_minor:
        type: integer
      ground_injury_none:
        type: integer
      ground_injury_serious:
        type: integer
      ground_injury_unknown:
        type: integer
      id:
        type: integer
      location_city_name:
        type: string
      location_country_name:
        type: string
      location_state_name:
        type: string
      max_injury_level:
        type: string
      passenger_injury_fatal:
        type: integer
      passenger_injury_minor:
        type: integer
      passenger_injury_none:
        type: integer
      passenger_injury_serious:
        type: integer
      passenger_injury_unknown:
        type: integer
      remark_text:
        type: string
      updated:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: API server for airaccidentdata.com
  title: AirAccidentData API
  version: "1.0"
paths:
  /accidents:
    get:
      description: Get list of all aviation accidents with pagination
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of accidents per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AccidentResponse'
        "400":
          description: Invalid parameters
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get a list of accidents
      tags:
      - Accidents
  /accidents/id/{id}:
    get:
      description: Retrieve details of an accident by its ID
      parameters:
      - description: Accident ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AircraftAccident'
        "400":
          description: Invalid accident ID
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Accident not found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get an accident by ID
      tags:
      - Accidents
  /aircrafts:
    get:
      description: Retrieve a list of all aircraft.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Aircraft'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get a list of aircrafts
      tags:
      - Aircrafts
  /aircrafts/{registration_number}/accidents:
    get:
      description: Get details of an aviation accident by its registration number
      parameters:
      - description: Registration number of the aircraft
        in: path
        name: registration_number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Accident details
          schema:
            $ref: '#/definitions/models.AccidentDetailResponse'
        "400":
          description: Invalid registration number
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Accident not found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get a list of accidents by aircraft registration number
      tags:
      - Aircrafts
  /aircrafts/details/{id}:
    get:
      description: Retrieve details of an aircraft by its ID
      parameters:
      - description: Aircraft ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Aircraft'
        "400":
          description: Invalid aircraft ID
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Aircraft not found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get details about an aircraft by ID
      tags:
      - Aircrafts
swagger: "2.0"
