basePath: /api/v1
definitions:
  models.Accident:
    properties:
      aircraft_damage_description:
        type: string
      aircraft_id:
        type: integer
      aircraft_missing_flag:
        type: string
      entry_date:
        type: string
      event_local_date:
        type: string
      event_local_time:
        type: string
      event_type_description:
        type: string
      far_part:
        type: string
      fatal_flag:
        type: string
      flight_activity:
        type: string
      flight_number:
        type: string
      flight_phase:
        type: string
      fsdo_description:
        type: string
      id:
        type: integer
      location_id:
        type: integer
      remark_text:
        type: string
      updated:
        type: string
    type: object
  models.AccidentPaginatedResponse:
    properties:
      accidents:
        items:
          $ref: '#/definitions/models.Accident'
        type: array
      limit:
        type: integer
      page:
        type: integer
      total:
        type: integer
    type: object
  models.Aircraft:
    properties:
      aircraft_make_name:
        type: string
      aircraft_model_name:
        type: string
      aircraft_operator:
        type: string
      id:
        type: integer
      registration_number:
        type: string
    type: object
  models.AircraftImage:
    properties:
      aircraft_id:
        type: integer
      id:
        type: integer
      image_url:
        type: string
      s3_url:
        type: string
    type: object
  models.AircraftPaginatedResponse:
    properties:
      aircrafts:
        items:
          $ref: '#/definitions/models.Aircraft'
        type: array
      limit:
        type: integer
      page:
        type: integer
      total:
        type: integer
    type: object
  models.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  models.Injury:
    properties:
      accident_id:
        type: integer
      count:
        type: integer
      id:
        type: integer
      injury_severity:
        type: string
      person_type:
        type: string
    type: object
  models.Location:
    properties:
      city_name:
        type: string
      country_name:
        type: string
      id:
        type: integer
      latitude:
        type: number
      longitude:
        type: number
      state_name:
        type: string
    type: object
info:
  contact: {}
  description: This is the server for managing air accident data.
  title: Air Accident Data API
paths:
  /accidents:
    get:
      description: Get a list of all aviation accidents with pagination.
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of accidents per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Accidents data with pagination details
          schema:
            $ref: '#/definitions/models.AccidentPaginatedResponse'
        "400":
          description: Invalid parameters
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get a list of accidents
      tags:
      - Accidents
  /accidents/{id}:
    get:
      description: Retrieve details of an accident by its ID
      parameters:
      - description: Accident ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Detailed accident data
          schema:
            $ref: '#/definitions/models.Accident'
        "400":
          description: Invalid accident ID
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Accident not found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get an accident by ID
      tags:
      - Accidents
  /accidents/{id}/injuries:
    get:
      description: Retrieve injury details for an accident based on the provided ID.
      parameters:
      - description: Accident ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of injuries associated with the accident
          schema:
            items:
              $ref: '#/definitions/models.Injury'
            type: array
        "400":
          description: Invalid accident ID provided
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: No injuries found for the specified accident ID
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get injuries for an accident
      tags:
      - Accidents
  /accidents/{id}/location:
    get:
      description: Retrieve location details of an accident by its ID
      parameters:
      - description: Accident ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Detailed location data
          schema:
            $ref: '#/definitions/models.Location'
        "400":
          description: Invalid accident ID
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Location not found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get location by accident ID
      tags:
      - Accidents
  /aircrafts:
    get:
      description: Retrieve a list of all aircrafts with pagination.
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of aircraft per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Aircrafts data with pagination details
          schema:
            $ref: '#/definitions/models.AircraftPaginatedResponse'
        "400":
          description: Invalid parameters
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get a list of aircrafts
      tags:
      - Aircrafts
  /aircrafts/{id}:
    get:
      description: Retrieve details of an aircraft by its ID
      parameters:
      - description: Aircraft ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Detailed aircraft data
          schema:
            $ref: '#/definitions/models.Aircraft'
        "400":
          description: Invalid aircraft ID
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Aircraft not found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get details about an aircraft by ID
      tags:
      - Aircrafts
  /aircrafts/{id}/images:
    get:
      description: Retrieve all images associated with a specific aircraft.
      parameters:
      - description: Aircraft ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of aircraft images
          schema:
            items:
              $ref: '#/definitions/models.AircraftImage'
            type: array
        "400":
          description: Invalid aircraft ID
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Aircraft not found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get all images for an aircraft
      tags:
      - Aircrafts
swagger: "2.0"
